#!/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby

def getc  # NOTE only tested on OS X
  system "/bin/stty raw -echo"
  if STDIN.respond_to?(:getbyte)
    STDIN.getbyte
  else
    STDIN.getc
  end
ensure
  system "/bin/stty -raw echo"
end

def wait_for_user
  puts
  puts "Press RETURN to continue or any other key to abort"
  # we test for \r and \n because some stuff does \r instead
  # as well as Y and y
  # abort unless [10, 13, 89, 121].include? getc
  [10, 13, 89, 121].include? getc
end

puts "ZenFresh Installer"

puts "Setup Git? [Y/n]"
if wait_for_user
  puts "yes, let's do it"
  puts "Enter your name:"
  `git config --global user.name "#{gets.chomp}"`
  puts "Enter your email:"
  `git config --global user.email "#{gets.chomp}"`

else
  puts "nope, not going to happen"
end

puts "Install Homebrew? [Y/n]"
if wait_for_user
  system('ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"')
end

puts "Update Homebrew? [Y/n]"
if wait_for_user
  system('brew update')
end

puts "Install Homebrew packages? [Y/n]"
if wait_for_user
  system('brew install htop')
  puts 'Running post-installation commands'
  system('sudo chown root:wheel /usr/local/Cellar/htop-osx/0.8.2.2/bin/htop')
  system('sudo chmod u+s /usr/local/Cellar/htop-osx/0.8.2.2/bin/htop')
end

puts "Install wget? [Y/n]"
if wait_for_user
  system('brew install wget')
end

puts "Install Homebrew Cask? [Y/n]"
if wait_for_user
  system('brew install caskroom/cask/brew-cask')
  system('brew cask doctor')
  system('brew cask update')
end

puts "Install Cask Packages? [Y/n]"
if wait_for_user
  system('brew cask install google-chrome')
  system('brew cask install hipchat')
  system('brew cask install atom')
  system('brew cask install skype')
  system('brew cask install Caskroom/cask/sequel-pro')
end

puts "Install Zsh? [Y/n]"
if wait_for_user
  system('brew install zsh')
end

puts "Install Pretzo? [Y/n]"
if wait_for_user

end

puts "Install Ruby? [Y/n]"
if wait_for_user
  system('brew install rbenv ruby-build')

  # git clone https://github.com/sstephenson/rbenv-gem-rehash.git ~/.rbenv/plugins/rbenv-gem-rehash
end

puts "Install SQLite3 [Y/n]"
if wait_for_user
  system('brew install sqlite3')
end

puts "Install MySQL [Y/n]"
if wait_for_user
  system('brew install mysql')
  system('ln -sfv /usr/local/opt/mysql/*.plist ~/Library/LaunchAgents')
  system('launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist')
  system('mysql_secure_installation')
end

puts "Install PostgreSQL [Y/n]"
if wait_for_user
  system('brew install postgresql')
  # system('ARCHFLAGS="-arch x86_64" gem install pg')
  # ln -sfv /usr/local/opt/postgresql/*.plist ~/Library/LaunchAgents
  # launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
end

puts "Done"
